name: "Solution1b"

on:
  pull_request:
    branches:
      - main

jobs:
  buildAndCheckAPIBreakage:
    name: Build and Check API Breakage
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Swift 5.9
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9.0"

    - name: Setup and Run Swift API Diff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Swift version: $(swift --version)"
        echo "Swift package manager version: $(swift package --version)"
        swift package resolve

        # Ensure we are in the correct directory
        cd $GITHUB_WORKSPACE

        # Run swift-api-diff commands here directly
        OLD_API_DIR=$(mktemp -d)
        NEW_API_DIR=$(mktemp -d)
        REPORT_DIR=$(mktemp -d)
        SDK_PATH=$(xcrun --show-sdk-path)

        echo "Fetching old version..."
        git checkout ${{ github.event.pull_request.base.sha }}
        swift build > /dev/null 2>&1 || { echo "Failed to build old version"; exit 1; }
        swift api-digester -sdk "$SDK_PATH" -dump-sdk -module "Amplify" -o "$OLD_API_DIR/old.json" -I .build/debug || { echo "Failed to dump old SDK"; exit 1; }
        
        echo "Fetching new version..."
        git checkout ${{ github.sha }}
        git log -1  # Print the commit info for debugging
        swift build> /dev/null 2>&1 || { echo "Failed to build new version"; exit 1; }
        swift api-digester -sdk "$SDK_PATH" -dump-sdk -module "Amplify" -o "$NEW_API_DIR/new.json" -I .build/debug || { echo "Failed to dump new SDK"; exit 1; }
        
        echo "Comparing APIs..."
        swift api-digester -sdk "$SDK_PATH" -diagnose-sdk --input-paths "$OLD_API_DIR/old.json" -input-paths "$NEW_API_DIR/new.json" > api-diff-report.txt

        # Print API diff report and capture the output for commenting
        cat api-diff-report.txt
        api_diff_output=$(cat api-diff-report.txt)
        echo "api_diff_output=$api_diff_output" >> $GITHUB_ENV

        # Comment on PR with API Diff
        if [[ $api_diff_output || $? -ne 0 ]]; then
          echo "Posting API Diff report to PR..."
          const issueNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const github = require('@actions/github');

          const octokit = new github.GitHub(process.env.GITHUB_TOKEN);

          const apiDiffOutput = process.env.api_diff_output;

          if (apiDiffOutput) {
            octokit.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              body: `### API Diff Report\n\`\`\`\n${apiDiffOutput}\n\`\`\``
            });
          } else {
            console.log("No API diff output found.");
          }
        else
          echo "No API diff output found. Exiting..."
          exit 0
