name: "SwiftAPIBreakage"

on:
  pull_request:
    branches:
      - main

jobs:
  buildAndCheckAPIBreakage:
    name: Build and Check API Breakage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

    - name: Install Swift 5.9
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9.0"

    - name: Get Swift version
      run: swift --version

    - name: Setup and Run Swift API Diff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Swift version: $(swift --version)"
        echo "Swift package manager version: $(swift package --version)"
        swift package resolve
        
        # Ensure we are in the correct directory
        cd $GITHUB_WORKSPACE
        
        # Run swift-api-diff commands here directly
        OLD_API_DIR=$(mktemp -d)
        NEW_API_DIR=$(mktemp -d)
        
        echo "Fetching old version..."
        git checkout ${{ github.event.pull_request.base.sha }}
        swift build
        swift api-digester -dump-sdk -module "Amplify -o "$OLD_API_DIR/old.json"

        echo "Fetching new version..."
        git checkout ${{ github.sha }}
        swift build
        swift api-digester -dump-sdk -module "Amplify" -o "$NEW_API_DIR/new.json"

        echo "Comparing APIs..."
        swift api-digester -diagnose-sdk --input-paths "$OLD_API_DIR/old.json" -input-paths "$NEW_API_DIR/new.json" > "$REPORT_DIR/api-diff-report.txt"
    
    - name: Upload API Diff Report
      uses: actions/upload-artifact@v3
      with:
        name: api-diff-report
        path: $REPORT_DIR/api-diff-report.txt
