name: "SwiftAPIBreakage"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main

jobs:
  buildAndCheckAPIBreakage:
    name: buildAndCheckAPIBreakage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
    - name: Install swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9.0"
    - name: Get swift version
      run: swift --version 

    - name: Swift API Diff
      uses: rozaychen/swift-api-diff@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
